[package]
name = "budgr"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = { version = "1.0.122", features = ["std"] }
glob = "0.3.1"
dirs = "5.0.1"
color-eyre = "0.6.3"
ratatui = "0.28.0"
crossterm = "0.25"
